// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0HeFETsbrTySa0CbK2ODbJr6n_wQtr8Q',
    appId: '1:349013216219:web:e9ff7e350a89d2ba6975fe',
    messagingSenderId: '349013216219',
    projectId: 'pruebachilin',
    authDomain: 'pruebachilin.firebaseapp.com',
    storageBucket: 'pruebachilin.appspot.com',
    measurementId: 'G-FZRQ28WHLT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOLQG0KfWJ1sdMF3g_kp4gDzrWkSnTbXE',
    appId: '1:349013216219:android:b7aa8c1720a07ca06975fe',
    messagingSenderId: '349013216219',
    projectId: 'pruebachilin',
    storageBucket: 'pruebachilin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMTj8equSvS5HyxOUt-DLs41IVGHQECfU',
    appId: '1:349013216219:ios:0ee4773c5762377c6975fe',
    messagingSenderId: '349013216219',
    projectId: 'pruebachilin',
    storageBucket: 'pruebachilin.appspot.com',
    iosBundleId: 'com.example.administrador',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMTj8equSvS5HyxOUt-DLs41IVGHQECfU',
    appId: '1:349013216219:ios:0ee4773c5762377c6975fe',
    messagingSenderId: '349013216219',
    projectId: 'pruebachilin',
    storageBucket: 'pruebachilin.appspot.com',
    iosBundleId: 'com.example.administrador',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0HeFETsbrTySa0CbK2ODbJr6n_wQtr8Q',
    appId: '1:349013216219:web:ab6b27138f7c8c266975fe',
    messagingSenderId: '349013216219',
    projectId: 'pruebachilin',
    authDomain: 'pruebachilin.firebaseapp.com',
    storageBucket: 'pruebachilin.appspot.com',
    measurementId: 'G-W1KERMWCXG',
  );
}
